[package]
name = "wasm-std"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[dependencies]
wasm-alloc = { path = "alloc" }
tiny-keccak = "1.3"

[dependencies.bigint]
version = "4"
default-features = false
